[general]
import = ["~/.config/alacritty/gruvbox_dark.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.0
offset = { x = 0, y = 2 }

[[hints.enabled]]
regex = "[a-f0-9]{40}|[a-f0-9]{7}"
action = "Copy"
mouse.enabled = true

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"
mode = "~Alt"

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
